name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'VERSION'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: Loeffelhardt/el-github-tag-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_ACTOR: loeffelhardt-bot
